### ISSUE TITLE
Unable to create an object of type 'ApplicationDbContext'

### ISSUE THREAD

**Issue by aleem604** [fullstackhero/docs#119]
on running the command
dotnet ef migrations add "brand_extend" --project ./src/Migrators/Migrators.PostgreSQL/ --context ApplicationDbContext -o Migrations/Application
 
return error
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

the command provided in documentation
dotnet ef migrations add "brand_extend" --project .././Migrators/Migrators.PostgreSQL/ --context ApplicationDbContext -o Migrations/Application

 returns
No project was found in directory '.././Migrators/Migrators.PostgreSQL/'.

is that a known bug
I am trying to use this template for my MVP
Please help me if I am doing something wrong
thanks

**Comment by iammukeshm** [comment]
from which directory are you running this command from?

**Comment by iammukeshm** [comment]
It has to be executed from the host directory.

`dotnet ef migrations add <CommitMessage> --project .././Migrators/Migrators.<Provider>/ --context ApplicationDbContext -o Migrations/Application`
