### ISSUE TITLE
Where is the "dotnet-webapi-boilerplate" repo?

### ISSUE THREAD

**Issue by mcyenikoylu** [fullstackhero/docs#201]
## Description

I can't find the "dotnet-webapi-boilerplate" repo mentioned on the website and in the documentation. Has the name changed?

### Steps to reproduce

- https://fullstackhero.net/dotnet-webapi-boilerplate/general/getting-started/
- https://github.com/fullstackhero/docs/blob/main/content/en/dotnet-webapi-boilerplate/general/getting-started/index.md

**Comment by iammukeshm** [comment]
Here is the repo: https://github.com/fullstackhero/dotnet-starter-kit
