### ISSUE TITLE
Update NET 8  dotnet-webapi-boilerplate 

### ISSUE THREAD

**Issue by Hoai-Phong** [fullstackhero/docs#202]
Is there a net 8 update now? 
https://fullstackhero.net/dotnet-webapi-boilerplate/general/getting-started/

**Comment by iammukeshm** [comment]
Yeah, https://github.com/fullstackhero/dotnet-starter-kit

Doc website work is in progress @ https://fullstackhero.pages.dev/dotnet-starter-kit/general/getting-started/
