### ISSUE TITLE
[Documentation] Update Documentation of Project Dependencies

### ISSUE THREAD

**Issue by mvarga6** [fullstackhero/docs#54]
The documentation on project structure refers to the `Core/Application` project as having no dependencies. 

> Note that the Application project does not depend on any other project.

This is no longer a true statement.

Looking at `Application.csproj`:
```xml
<ItemGroup>
    <ProjectReference Include="..\..\Core\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.DTOs\Shared.DTOs.csproj" />
</ItemGroup>
```

But also we see the dependency in the interfaces of the services in the Application project. For example, in the `IBrandService.cs` interface 
```csharp
public interface IBrandService : ITransientService
{
    Task<PaginatedResult<BrandDto>> SearchAsync(BrandListFilter filter);
    // ...
}
```
the argument and template type in the returned object are from the shared project.

_I feel_ this is important for new comers to know and understand _why_ this dependency exists.  For instance, I found it a little confusing as to why services in the application layer are returning DTO types, and not Domain types.

Updating the documentation to reflect the current state of the template and extending the rationale for these choices would be super helpful and appreciated!!!

**Comment by iammukeshm** [comment]
updated
