### ISSUE TITLE
[Documentation] Application project does not depend on any other project

### ISSUE THREAD

**Issue by dandohotaru** [fullstackhero/docs#88]
on the project structure [page](https://github.com/fullstackhero/docs/blob/main/content/en/dotnet-webapi-boilerplate/general/project-structure/index.md) it is stated that
> Note that the Application project does not depend on any other project.
> ...
> Note that the Domain project does not depend on any other project.

I would assume that to be true for the `domain` but maybe not so much for the `application` project

Checking the actual source code for the [application.csproj](https://github.com/fullstackhero/dotnet-webapi-boilerplate/blob/main/src/Core/Application/Application.csproj) seems to imply that the `application` actually depends on `domain` as expected

```
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>
```

**Comment by iammukeshm** [comment]
updated
